"""
This file is executed on startup, and creates a menu entry for our plugin
"""
import unreal


section_name = 'Python'
se_command = 'import unreal_script_editor;w = unreal_script_editor.show()'  # todo replace with your code
label = 'Python script editor'
tooltip = "A Python script editor to write & run Python code"


def add_cmd_to_menu(label=None, command=None, tooltip=None, icon=None):
    unreal_menus = unreal.ToolMenus.get()
    parent_menu = unreal_menus.find_menu("LevelEditor.MainMenu.Tools")

    # name kwargs needs to be unique! if not set, it's autogenerated
    entry = unreal.ToolMenuEntry(
        type=unreal.MultiBlockType.MENU_ENTRY,
        insert_position=unreal.ToolMenuInsert("", unreal.ToolMenuInsertType.FIRST),
    )
    if label:
        entry.set_label(label)
    if command:
        entry.set_string_command(
            type=unreal.ToolMenuStringCommandType.PYTHON,
            string=command,
            custom_type=unreal.Name("_placeholder_"),
        )
    if tooltip:
        entry.set_tool_tip(tooltip)
    if icon:
        entry.set_icon(icon)

    parent_menu.add_menu_entry("Configuration", entry)


add_cmd_to_menu(label=label, command=se_command, tooltip=tooltip)
